# -*- coding: utf-8 -*-
"""Gurobi & Python. Vehicle Routing Problem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16wo6TMAMwO28T1abTHnhgM9XmXYuarBS
"""

import numpy as np
import matplotlib.pyplot as plt

rnd = np.random
rnd.seed(4)

import pandas as pd

dataset = pd.read_excel("D:\Kerjaan\Python Gurobi VRP\OK 18 new2. VRP.xlsx")

dataset

n = 20 # number of clients
m = 5 # jumlah kurir
xc = rnd.rand(n+1)*200
yc = rnd.rand(n+1)*100

plt.plot(xc[0],yc[0],c='r',marker='s')
plt.scatter(xc[1:],yc[1:],c='b')

"""Tujuan yang ingin dicapai adalah meminimumkan biaya. Kemudian meningkatkan atau menurunkan konstrain atau fungsi kendala, sehingga kapasitasnya bisa dimaksimalkan dengan biaya yang minimum."""

N = [i for i in range(1,n+1)] # Nomor klien
V = [0] + N # Nomor simpul
A = [(i,j) for i in V for j in V if i!=j] # Nomor jalur
D = {(i,j): np.hypot(xc[i]-xc[j],yc[i]-yc[j]) for i,j in A} # Biaya
U = 20 # Jumlah kapasitas kendaraan
q = {i: rnd.randint(1,20) for i in N} # Jumlah barang yang harus diantar
                                      #untuk pelanggan ke-i
K = [k for k in range(1,m+1)] # Nomor kurir
Ut = 10 # menit
t = {(i,j,k): rnd.randint(1,10) for i,j in A for k in K}
St = 10 #menit
st = {i: rnd.randint(1,10) for i in N} # Jumlah waktu pelayanan untuk pelanggan ke-i
Vl = 30 #km/h
vl = {k: rnd.randint(20,30) for k in K}

pip install gurobipy

from gurobipy import Model, GRB, quicksum

mdl = Model('VRP')

x = mdl.addVars(A,K, vtype=GRB.BINARY)
u = mdl.addVars(N, vtype = GRB.CONTINUOUS)

mdl.modelSense = GRB.MINIMIZE
mdl.setObjective(quicksum(x[i,j,k]*D[i,j] for i,j in A for k in K))

mdl.addConstrs(quicksum(x[i, j, k] for j in V for k in K if j != i) == 1 for i in N)
mdl.addConstrs(quicksum(x[i, j, k] for i in V for k in K if i != j) == 1 for j in N)
mdl.addConstrs((x[i, j, k] == 1) >> (u[i] + q[i] == u[j]) for i, j in A for k in K if i != 0 and j != 0)
mdl.addConstrs(u[i] >= q[i] for i in N)
mdl.addConstrs(u[i] <= U for i in N)
mdl.addConstrs(quicksum(t[i,j,k]*x[i, j, k] for i,j in A for k in K) <= Ut for i,j in A for k in K)
mdl.addConstrs(quicksum(vl[k]*x[i, j, k] for i,j in A for k in K)<= Vl for i,j in A for k in K)
mdl.addConstrs(st[l]*x[i,j,k] <= St for l in N for i,j in A for k in K)

mdl.optimize()

active_arcs = [a for a in A if x[a].x>0.99]

active_arcs

for i,j in active_arcs:
  plt.plot([xc[i],xc[j]],[yc[i],yc[j]],c='g',zorder=0)
plt.plot(xc[0],yc[0],c='r',marker='s')
plt.scatter(xc[1:],yc[1:],c='b')